### ISSUE TITLE
Add more cycles to test

### ISSUE THREAD

**Issue by hkirsman** [aleksijohansson/drupal-project#235]
Currently we only have 50 requests and on faster computer these finish around 5.5 seconds. If we would increase the time, then we could see more clearly how much difference there is.

**Comment by aleksijohansson** [comment]
The setups have really gotten faster if I remember correctly what they were in the beginning. I agree, it makes sense to increase the amount of requests 👍

**Comment by hkirsman** [comment]
Closing this in favor of https://github.com/aleksijohansson/drupal-benchmark/issues/236
